name: Workflow to deploy Terraform

on:
  [push]


jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "./infrastructure/"
    env:
      AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Compress Lambda code to be used in Terraform
        run: zip asg_instance_refresh.zip asg_instance_refresh.py

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1.2.1

      - name: Terraform init
        run: terraform init

      - name: Terraform file validation
        run: terraform validate

      - name: Display the plan
        run: terraform plan

      - name: Apply terraform
        run: terraform apply -auto-approve